baseURI: ""
makeFolders: false
smtpServer: smtp.zoho.com
emailPassword:
toEmailAddress:
fromEmailAddress:
allowEmails: false
subject: "Music downloaded %s"
downloadLedger: ledger.txt
dbaEnabled: true
dba: postgres
configEnabled: true
configLocation: config.yml
copyConfigToDataBase: true
removeOldConfig: false
copyDatabaseToCondig: false
name:
password:
host:
database: